$.fn.maphilight.defaults = {
  fill: true,
  fillColor: 'D9FA37',
  fillOpacity: 0.3,
  stroke: false,
  strokeColor: 'rgba(200,200,200,0.5)',
  strokeOpacity: 1,
  strokeWidth: 1,
  fade: true,
  alwaysOn: false,
  neverOn: false,
  groupBy: false,
  wrapClass: true,
  shadow: true,
  shadowX: 10,
  shadowY: 10,
  shadowRadius: 6,
  shadowColor: '000000',
  shadowOpacity: 0.8,
  shadowPosition: 'outside',
  shadowFrom: true ,
}